server:
  port: 8081
  servlet:
    context-path: /ms
# 本地yy
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/testHeartbeat
#    username: root
#    password: Reborn22
#    driver-class-name: com.mysql.cj.jdbc.Driver

# 服务器
# - 正式库
#spring:
#  datasource:
#    url: jdbc:mysql://101.133.131.175:3306/heartbeat
#    username: ecStu
#    password: SuperGift#123
#    driver-class-name: com.mysql.cj.jdbc.Driver

# 服务器
# - 测试库
spring:
  datasource:
    url: jdbc:mysql://101.133.131.175:3306/testHeartbeat
    username: ecStu
    password: SuperGift#123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB

mybatis:
  mapper-locations: classpath:mapper/*.xml

# jwt配置
jwt:
  config:
    secret: heartbeat
    ttl: 7200


# MP 显示运行日志参数
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

# 文件上传
file:
  local_path: /Users/jennifer/Desktop/upload
  server_path: /opt/hb/upload