
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testHeartbeat
    username: root
    password: Reborn22
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

# jwt配置
jwt:
  config:
    secret: heartbeat
    ttl: 3000